#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

---
apiVersion: v1
kind: Namespace
metadata:
  name: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"Service", "metadata":{"name":"source-controller"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace

#@overlay/match by=overlay.subset({"kind":"Deployment", "metadata":{"name":"source-controller"}})
---
metadata:
  #@overlay/match missing_ok=True
  namespace: #@ data.values.namespace
