#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#! When working with OCIRepositories, the Flux Source Controller
#! requires permissions to read ServiceAccounts objects.

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fluxcd-source-sa-role
  namespace: #@ data.values.namespace
rules:
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - get
      - list
      - watch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluxcd-source-sa-rolebinding
  namespace: #@ data.values.namespace
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluxcd-source-sa-role
subjects:
  - kind: ServiceAccount
    name: default
    namespace: #@ data.values.namespace
