#@data/values-schema
---

#@schema/desc "The namespace where to install FluxCD Source Controller."
namespace: flux-source-system

#@schema/desc "Settings for the Kyverno policies."
policies:
  #@schema/desc "Whether to include the out-of-the-box Kyverno policies to validate and secure the package installation."
  include: false

#@schema/desc "Resource configuration for the source-controller Deployment."
resources:
  #@schema/desc "Resource limits configuration for the `source-controller` Deployment."
  limits:
    #@schema/desc "CPU limits configuration for the `source-controller` Deployment."
    cpu: 1000m
    #@schema/desc "Memory limits configuration for the `source-controller` Deployment."
    memory: 1Gi

#@schema/desc "Port configuration for the `source-controller` Service."
service_port: 80

#@schema/desc "Settings for the corporate proxy."
proxy:
  #@schema/desc "The HTTPS proxy to use for network traffic."
  https_proxy: ""
  #@schema/desc "The HTTP proxy to use for network traffic."
  http_proxy: ""
  #@schema/desc "A comma-separated list of hostnames, IP addresses, or IP ranges in CIDR format that should not use the proxy."
  no_proxy: ""
