#@data/values-schema
---

#@schema/desc "The namespace where to install FluxCD Source Controller."
namespace: flux-system

#@schema/desc "Settings for the Kyverno policies."
policies:
  #@schema/desc "Whether to include the out-of-the-box Kyverno policies to validate and secure the package installation."
  include: false

#@schema/desc "Resource configuration for the source-controller Deployment."
resources:
  #@schema/desc "Resource limits configuration for the `source-controller` Deployment."
  limits:
    #@schema/desc "CPU limits configuration for the `source-controller` Deployment."
    cpu: 1000m
    #@schema/desc "Memory limits configuration for the `source-controller` Deployment."
    memory: 1Gi

#@schema/desc "Port configuration for the `source-controller` Service."
service_port: 80

#@schema/desc "Settings for the corporate proxy."
proxy:
  #@schema/desc "The HTTPS proxy to use for network traffic."
  https_proxy: ""
  #@schema/desc "The HTTP proxy to use for network traffic."
  http_proxy: ""
  #@schema/desc "A comma-separated list of hostnames, IP addresses, or IP ranges in CIDR format that should not use the proxy."
  no_proxy: ""

#@schema/desc "Logging configuration."
logging:
  #@schema/desc "Log verbosity level. Options: `trace`, `debug`, `info`, `error`."
  #@schema/validation one_of=["trace", "debug", "info", "error"]
  level: info
  #@schema/desc "Log encoding format. Options: `console`, `json`."
  #@schema/validation one_of=["console", "json"]
  encoding: json

#@schema/desc "Leader election configuration."
leader_election:
  #@schema/desc "Interval at which non-leader candidates will wait to force acquire leadership."
  lease_duration: "35s"
  #@schema/desc "Defines if the leader should step down voluntarily on controller manager shutdown."
  release_on_cancel: "true"
  #@schema/desc "Duration that the leading controller manager will retry refreshing leadership before giving up."
  renew_deadline: "30s"
  #@schema/desc "Duration the LeaderElector clients should wait between tries of actions."
  retry_period: "5s"
